apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: nginx-gateway
data:
  nginx.conf: |
    load_module /usr/lib/nginx/modules/ngx_http_js_module.so;

    
    events {}

    pid /etc/nginx/nginx.pid;
    error_log stderr debug;

    http {
      include /etc/nginx/conf.d/*.conf;
      js_import /usr/lib/nginx/modules/njs/httpmatches.js;
      proxy_headers_hash_bucket_size 512;
      proxy_headers_hash_max_size 1024;
      server_names_hash_bucket_size 256;
      server_names_hash_max_size 1024;
      variables_hash_bucket_size 512;
      variables_hash_max_size 1024;
    
      server {
        listen 80;
        location /nginx_status { 
            stub_status; 
        } 
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-otelconf
  namespace: nginx-gateway
data:
  opentelemetry_module.conf: |
    NginxModuleEnabled ON;
    NginxModuleOtelSpanExporter otlp;
    NginxModuleOtelExporterEndpoint oteld-collector.default.svc.cluster.local:4317;
    NginxModuleServiceName nginx-gateway;
    NginxModuleServiceNamespace nginx-gateway;
    NginxModuleServiceInstanceId DemoInstanceId;
    NginxModuleResolveBackends ON;
    NginxModuleTraceAsError ON;
    
