apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: nginx-gateway
data:
  nginx.conf: |
    load_module /usr/lib/nginx/modules/ngx_http_js_module.so;
    load_module /opt/opentelemetry-webserver-sdk/WebServerModule/Nginx/1.23.1/ngx_http_opentelemetry_module.so;
    
    events {}

    pid /etc/nginx/nginx.pid;
    error_log stderr debug;

    http {
      include /etc/nginx/conf.d/*.conf;
      js_import /usr/lib/nginx/modules/njs/httpmatches.js;
      proxy_headers_hash_bucket_size 512;
      proxy_headers_hash_max_size 1024;
      server_names_hash_bucket_size 256;
      server_names_hash_max_size 1024;
      variables_hash_bucket_size 512;
      variables_hash_max_size 1024;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
    
    
      server {
        listen 80;
        server_name nginxgateway;
        
        
        location /nginx_status { 
            stub_status; 
        } 
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-otelconf
  namespace: nginx-gateway
data:
  otel-nginx.toml: |
    exporter = "otlp"
    processor = "batch"
  
    [exporters.otlp]
  
    [processors.batch]
    max_queue_size = 2048
    schedule_delay_millis = 5000
    max_export_batch_size = 512
  
    [service]
    name = "nginx-proxy" 
    
